services:
# Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    container_name: villanueva_db
    environment:
      POSTGRES_DB: villanueva_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

# Django app
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_villanueva_backend
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=0
      - IP_BASE_URL=192.168.100.4
    depends_on:
      - db
    command: gunicorn villanueva_project.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

  # Scheduler para actualizar cuotas vencidas diariamente
  scheduler:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: villanueva_scheduler
    volumes:
      - ./backend:/app
      - ./media_volume:/app/media
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=0
      - IP_BASE_URL=192.168.100.4
    depends_on:
      - db
    command: >
      sh -c "echo 'Scheduler iniciado - Actualizando cuotas cada 24 horas' &&
      while true; do
        python manage.py update_overdue_installments;
        sleep 86400;
      done"
    restart: always