services:
# Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    container_name: villanueva_db
    environment:
      POSTGRES_DB: villanueva_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

# Django app
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_villanueva_backend
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    environment:
      - DEBUG=0
    depends_on:
      - db
    command: gunicorn villanueva_project.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: villanueva_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://0.0.0.0:8000
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend